### ISSUE TITLE
Generadores

### ISSUE THREAD

**Issue by juancuiule** [Ignaciodettler/tplogico#3]
https://github.com/Ignaciodettler/tplogico/blob/2ff1cf08bbdae98c3021873dc1ce2b95b8893c2c/tplogico.pl#L149
https://github.com/Ignaciodettler/tplogico/blob/2ff1cf08bbdae98c3021873dc1ce2b95b8893c2c/tplogico.pl#L161
https://github.com/Ignaciodettler/tplogico/blob/2ff1cf08bbdae98c3021873dc1ce2b95b8893c2c/tplogico.pl#L165

En esos tres predicados que usan dentro del punto de `elGrandCandidato` están generando al candidato.

No esta necesariamente mal, pero quiero saber por qué lo hacen?

**Comment by thomykut** [comment]
lo cambio, dejo el issue abierto pq no se si preferis como esta ahora o como estaba antes
