### ISSUE TITLE
elGranCandidato

### ISSUE THREAD

**Issue by juancuiule** [Ignaciodettler/tplogico#4]
Recién me doy cuenta que esta parte del enunciado puede tener dos interpretaciones posibles para:

`Para todas las provincias en las cuales su partido compite, el mismo gana.`

Podemos leerlo como que el **candidato** tiene que ganar o que el **partido**.

¿Cómo lo interpretaron ustedes? En base a eso puedo saber si lo que hicieron va de la mano con esa interpretacion.

```prolog
ganaEnDondeSePostula(UnCandidato):-
	esCandidato(UnCandidato, UnPartido),
	forall(sePostula(UnPartido, Provincia),ganaEnXProvincia(UnCandidato, Provincia)).

ganaEnXProvincia(UnCandidato, Provincia):-
	esCandidato(UnCandidato, UnPartido),
	sePostula(UnPartido, Provincia),
        forall(esCandidato(OtroCandidato, _), leGanaA(UnCandidato, OtroCandidato, Provincia)).
```

**Comment by thomykut** [comment]
lo hicimos por candidato, dejo issue abierto a otra pregunta

**Comment by thomykut** [comment]
mejor lo cambio a partido, tendria mas logica ya que un candidato no deberia postularse en varias provincias, supongo..
