### ISSUE TITLE
Se está generando demás

### ISSUE THREAD

**Issue by natoszme** [Ignaciodettler/tplogico#9]
Porque intencionDeVotoEn ya liga al partido y a la provincia @Ignaciodettler @thomykut @Fruk0 

https://github.com/Ignaciodettler/tplogico/blob/186b5bb18874fec9a41353700dec70266adf8cc8/TP%20LOGICO.pl#L169

**Comment by thomykut** [comment]
por que? tomamos como si intencionDeVotoEn ya lo generara?

**Comment by natoszme** [comment]
Claro. Qué aportaría usar sePostula además de intencionDeVotoEn?

**Comment by thomykut** [comment]
Perfecto
